- name: Logstash config copy
  ansible.builtin.template:
   src: logstash.conf
   dest: /etc/logstash/conf.d/logstash.conf

- name:  restart Logstash
  ansible.builtin.systemd:
   name: logstash
   state: restarted
   enabled: yes